### ISSUE TITLE
Catching Exception

### ISSUE THREAD

**Issue by neoxharsh** [waveform80/picamera#436]
I have been trying to update an overlay, the overlay is updated perfectly but it keeps on throwing an exception 
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 1227, in wrapper
    self._pool.send_buffer(block=False)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 1931, in send_buffer
    super(MMALPortPool, self).send_buffer(port, block, timeout)
  File "/usr/lib/python2.7/dist-packages/picamera/mmalobj.py", line 1881, in send_buffer
    raise PiCameraMMALError(mmal.MMAL_EAGAIN, 'no buffers available')
picamera.exc.PiCameraMMALError: no buffers available: Resource temporarily unavailable; try again later
```
I tried catching the exception, but somehow I am not able to catch it. It seems like the exception is raised from the c-library.

**Comment by waveform80** [comment]
Possibly related to #320 if you're updating the overlay too quickly?
