### ISSUE TITLE
i am facing issue with Usb Webcam using rasberypi in opencv python.

### ISSUE THREAD

**Issue by AafaqueAli** [waveform80/picamera#602]
Hello please help me i am doing my final year project its about face recognition all system is going well but i am not able to use webcam video/image in rasbery pi4 using python.
same code is working in Laptop but not working in RasberyPi .
errors are :
select timeout
Traceback (most recent call last):
  File "final.py", line 83, in run
    self.myCamFun()
  File "final.py", line 106, in myCamFun
    print(frame.shape)
AttributeError: 'NoneType' object has no attribute 'shape'
Aborted

cap = cv2.VideoCapture(0) this line is working  ok in Macbook but working in  R.Pi .

**Comment by AafaqueAli** [comment]
cap = cv2.VideoCapture("location of images i want to use") if i use line it is working, it means frame can not open from webcam to  capture video or images.
