### ISSUE TITLE
PiCameraRuntimeError: Timed out waiting for a split point

### ISSUE THREAD

**Issue by olivermolteno** [waveform80/picamera#610]
Hi I'm using a Pi 4B to do some recording across multiple files in 'mjpeg' format with size (1296 x 972) and using `camera.split_record()` and the time to split the recording is very inconsistent, can easily lead to up to 5 seconds of frame loss whenever `camera.split_record()` is called. I've checked to see if its a problem getting key frames or waiting for a lock but the lock is always aquired very quickly, it also depends on the length of the split files. Longer files usually take longer (obviously to be expected) but the timing is very inconsistent. 
Here is a sample of times to split recording for a 1 second recording and a 3 min recording.
###### 2.0449461936950684
0.08181262016296387
0.23624801635742188
0.17154312133789062
0.17923641204833984
###### 0.784857988357544
0.0020685195922851562

###### 0.6338062286376953
0.056494712829589844
0.010864973068237305
0.03108811378479004
0.01169896125793457
0.02942204475402832
0.02547168731689453
0.02574300765991211
0.024487018585205078
0.023938894271850586
0.027276277542114258
0.023485660552978516
0.019032716751098633
0.023926496505737305
0.01997518539428711
0.02502608299255371
0.027965307235717773
0.025754928588867188
0.024860382080078125
0.03259706497192383
0.024240970611572266
0.014113426208496094
0.03014063835144043
0.021927833557128906
0.032946109771728516
0.01964402198791504
0.01966714859008789
0.01563429832458496
0.03059554100036621
###### 1.2485296726226807
0.01016855239868164
0.028683900833129883
0.0214385986328125
0.026909589767456055
0.02765202522277832
0.02385711669921875
0.028085947036743164
0.027007579803466797
0.022245407104492188
0.023446321487426758
0.0207669734954834
0.022284746170043945
0.027709007263183594
0.0229036808013916
0.022184371948242188
0.028692007064819336
0.02554011344909668
0.02205348014831543
0.028035879135131836
0.01533818244934082
0.02689385414123535
0.029204845428466797
###### 8.029193878173828
0.012573480606079102
0.026857614517211914
0.029825687408447266
0.0228116512298584
0.027724027633666992
0.02516341209411621
0.02918100357055664
0.02295541763305664
0.027877092361450195
0.020892620086669922

Each set of times is from the same recording.
Any ideas on how to fix this?

**Comment by julieta-311** [comment]
I'm getting this error on a Raspberry Pi 4 with a v2.1 8MP camera module when calling `record_sequence`. The Pi is running on `balenaOS 2.53.12+rev1` and the recorder script is being run by a parent process written in Go. It's set to write 1 minute long videos to memory, which are then handled by a separate process. Sometimes when the video handling fails, the files accumulate and it hits a `no space left on device` error. This restarts the execution of recorder.py, and after that we are intermittently getting `PiCameraRuntimeError: Timed out waiting for a split point`. 

```
2020-10-09T20:35:47.881377000Z ERROR | MainThread | root | Cannot write video, no space on device
2020-10-09T20:35:52.886275000Z Traceback (most recent call last):
2020-10-09T20:35:52.887425000Z   File "/recorder.py", line 224, in <module>
2020-10-09T20:35:52.888102000Z     main()
2020-10-09T20:35:52.888336000Z   File "/recorder.py", line 220, in main
2020-10-09T20:35:52.888513000Z     snapshot_thread.join(5)
2020-10-09T20:35:52.888662000Z   File "/usr/local/lib/python3.8/site-packages/picamera/camera.py", line 758, in __exit__
2020-10-09T20:35:52.889582000Z     self.close()
2020-10-09T20:35:52.889788000Z   File "/usr/local/lib/python3.8/site-packages/picamera/camera.py", line 737, in close
2020-10-09T20:35:52.891091000Z     self.stop_recording(splitter_port=port)
2020-10-09T20:35:52.891290000Z   File "/usr/local/lib/python3.8/site-packages/picamera/camera.py", line 1196, in stop_recording
2020-10-09T20:35:52.893237000Z     self.wait_recording(0, splitter_port)
2020-10-09T20:35:52.893445000Z   File "/usr/local/lib/python3.8/site-packages/picamera/camera.py", line 1167, in wait_recording
2020-10-09T20:35:52.895466000Z     encoder.wait(timeout)
2020-10-09T20:35:52.895699000Z   File "/usr/local/lib/python3.8/site-packages/picamera/encoders.py", line 398, in wait
2020-10-09T20:35:52.896480000Z     raise self.exception
2020-10-09T20:35:52.896675000Z   File "/usr/local/lib/python3.8/site-packages/picamera/encoders.py", line 267, in _callback
2020-10-09T20:35:52.897238000Z     stop = self._callback_write(buf)
2020-10-09T20:35:52.897417000Z   File "/usr/local/lib/python3.8/site-packages/picamera/encoders.py", line 921, in _callback_write
2020-10-09T20:35:52.898866000Z     return super(PiVideoEncoder, self)._callback_write(buf, key)
2020-10-09T20:35:52.898991000Z   File "/usr/local/lib/python3.8/site-packages/picamera/encoders.py", line 298, in _callback_write
2020-10-09T20:35:52.899259000Z     written = output.write(buf.data)
2020-10-09T20:35:52.899363000Z OSError: [Errno 28] No space left on device
2020-10-09T20:35:52.997682000Z run error: exit status 1
2020-10-09T20:36:52.998674000Z Running command: python3 /recorder.py
2020-10-09T20:36:53.700687000Z DEBUG | MainThread | root | Found camera imx219 (max 3280x2464)

...

2020-10-09T20:39:11.582150000Z ERROR | MainThread | root | Timed out waiting for a split point
2020-10-09T20:39:11.582444000Z Traceback (most recent call last):
2020-10-09T20:39:11.582597000Z   File "/recorder.py", line 210, in main
2020-10-09T20:39:11.582720000Z     record(camera, chunk_duration, output_dir, exit_event)
2020-10-09T20:39:11.582830000Z   File "/recorder.py", line 104, in record
2020-10-09T20:39:11.582938000Z     for filename in camera.record_sequence(
2020-10-09T20:39:11.583039000Z   File "/usr/local/lib/python3.8/site-packages/picamera/camera.py", line 1282, in record_sequence
2020-10-09T20:39:11.583143000Z     encoder.split(output)
2020-10-09T20:39:11.583261000Z   File "/usr/local/lib/python3.8/site-packages/picamera/encoders.py", line 857, in split
2020-10-09T20:39:11.583364000Z     raise PiCameraRuntimeError('Timed out waiting for a split point')
2020-10-09T20:39:11.583466000Z picamera.exc.PiCameraRuntimeError: Timed out waiting for a split point
````
